//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelos
    {
        public Modelos()
        {
            this.Automoviles = new HashSet<Automoviles>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int MarcaId { get; set; }
    
        public virtual ICollection<Automoviles> Automoviles { get; set; }
        public virtual Marcas Marcas { get; set; }
    }
}
